### ISSUE TITLE
Use semantic versioning

### ISSUE THREAD

**Issue by Ironholds** [wrathematics/dequer#1]
Friends don't let friends appear in violation of best practices ;)

**Comment by wrathematics** [comment]
I really should.  At some point I decided I would use MAJOR.MINOR for small packages, but it's kind of dumb.  I don't know what CRAN's policy is on changing versioning style though.  I assume anything satisfying `as.package_version(new) > as.package_version(old)` works?

**Comment by Ironholds** [comment]
Pretty much!

On Sunday, 5 July 2015, wrathematics notifications@github.com wrote:

> I really should. At some point I decided I would use MAJOR.MINOR for small
> packages, but it's kind of dumb. I don't know what CRAN's policy is on
> changing versioning style though. I assume anything satisfying as.package_version(new)
> 
> > as.package_version(old) works?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wrathematics/dequer/issues/1#issuecomment-118623395.

## 

Sent from my mobile computing device of Lovecraftian complexity and horror.

**Comment by wrathematics** [comment]
lol how is this still open.

Fixed in https://github.com/wrathematics/dequer/commit/4a9f87f34a53d9938ab99dbc0872e6e8646d70df
